#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Jonnie k

# Short bio or description (displayed in the header)
description: student with no coding skill running a blog about coding for some reason

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars3.githubusercontent.com/u/4943487?v=3&s=460

#
# Flags below are optional
#


